 # /var/run/docker.sock don't change it(in Linux)
 # /data portainer's datafile
version: "3"
services:
  app:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 8000:8000
      - 9000:9000
